# Generated by Django 4.2.1 on 2023-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_addimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='addImage',
        ),
        migrations.AddField(
            model_name='choice',
            name='addImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
