# Generated by Django 4.2.1 on 2023-05-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_addimage_choice_addimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='addImage',
        ),
    ]
