# Generated by Django 4.2.1 on 2023-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_addimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(default='choices/default.jpg', upload_to='choices/'),
        ),
    ]
